services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:latest
    container_name: homepage
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - homepage-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - homepage-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
      TZ: Asia/Seoul
    command: [ "redis-server", "--requirepass", "${REDIS_PASS}" ]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 5s
      retries: 10
    networks:
      - homepage-network
    restart: unless-stopped
    
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homepage-network
    restart: unless-stopped

networks:
  homepage-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
